# https://taskfile.dev
version: '3'

silent: true
tasks:
  unit-tests:
    cmds:
      - echo "- Запуск юнит-тестов"
      - |
        # go build -ldflags '-s -w -X main.buildVersion=1.0.0 -X main.buildDate=2023-01-23 -X main.buildCommit=0c2fs' -o cmd/shortener/shortener cmd/shortener/main.go
        go build -buildvcs=false  -o cmd/agent/agent cmd/agent/main.go
        go build -buildvcs=false -o cmd/server/server cmd/server/main.go
        # Запуск тестов
        metricstest -test.v -test.run=^TestIteration1$ -binary-path=cmd/server/server
        metricstest -test.v -test.run=^TestIteration2[AB]*$ -source-path=. -agent-binary-path=cmd/agent/agent
        metricstest -test.v -test.run=^TestIteration3[AB]*$ -source-path=. -agent-binary-path=cmd/agent/agent -binary-path=cmd/server/server
        metricstest -test.v -test.run=^TestIteration4$ -agent-binary-path=cmd/agent/agent -binary-path=cmd/server/server -server-port=35929 -source-path=.
        metricstest -test.v -test.run=^TestIteration5$ -agent-binary-path=cmd/agent/agent -binary-path=cmd/server/server -server-port=35929 -source-path=.
  static-tests:
    cmds:
      - echo "- Запуск статических тестов"
      - go vet -vettool=statictest ./...
