edition = "2023";

package metrilo;

option go_package = "github.com/fatkulllin/metrilo/pkg/proto;metrilo";
import "google/protobuf/go_features.proto";
option features.(pb.go).api_level = API_OPAQUE;

message Metric {
  string id = 1;        // имя метрики
  string type = 2;      // "gauge" или "counter"
  double value = 3;     // для gauge
  int64 delta = 4;      // для counter
}

message UpdateMetricsRequest {
  repeated Metric metrics = 1 [lazy = true];
}

message UpdateMetricsResponse {}

service MetricsService {
  rpc UpdateMetrics (UpdateMetricsRequest) returns (UpdateMetricsResponse);
}
